server:
  port: 8082
spring:
  application:
    name: api-service
  cloud:
    gateway:
      enabled: true
      routes:
        - id: user-service
          uri: http://127.0.0.1:8040
          predicates:
            - Path=/user/**,/code/**
        - id: article-service
          uri: lb://article-service
          predicates:
            - Path=/article/**
        - id: verification-service
          uri: http://127.0.0.1:8050
          predicates:
            - Path=/verification/**
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: simple_blog
  redis:
    host: 121.37.71.204
    port: 8888
    password: 18780269370lx
    database: 0
#白名单
request:
  white-list:
    - /user/signUp
    - /user/signIn
    - /code/phoneCode