server:
  port: 8020

spring:
  application:
    name: article-service
  profiles:
    active: dev
seata:
  enabled: true
  tx-service-group: default_tx_group
  service:
    vgroup-mapping:
      default_tx_group: default
