server:
  port: 8888

spring:
  application:
    name: rabbit-service
  rabbitmq:
    host: 1.15.153.44
    port: 5672
    username: liaoxin
    password: 18780269370lx
    publisher-confirm-type: correlated

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8001/eureka

